# - menu_name: ""

- name: "RSS"
  url: "/feed.xml"
  title: "通过 RSS 订阅本网站"

- name: "技术参数"
  url: "/specs/"
  title: "关于本网站的技术参数"

- name: "隐私权"
  url: "https://tlo.xyz/privacy-policy/zh-CN/"
  title: "关于隐私权"

- name: "捐助 (通过手机版支付宝)"
  url: "https://qr.alipay.com/ap9exv5cnp5mbofk4d"
  title: "感谢！"

- name: "捐助 (通过网页版支付宝)"
  url: "https://shenghuo.alipay.com/send/payment/fill.htm?optEmail=network@tlo.xyz&title=Domate%20ZE3kr"
  title: "感谢！"

- name: "捐助 (通过 PayPal/信用卡)"
  url: "https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=network@tlo.xyz&item_name=Donate+ZE3kr&currency_code=USD"
  title: "感谢！"