# - menu_name: ""

- name: "RSS"
  url: "/feed.xml"
  title: "通过 RSS 订阅本网站"

- name: "技术参数"
  url: "/specs/"
  title: "关于本网站的技术参数"

- name: "隐私权"
  url: "https://docs.tlo.xyz/wiki/TLO:Privacy_policy/zh-CN"
  title: "关于隐私权"

- name: "捐助"
  url: "/about/#section-3"
  title: "感谢！"
