# - menu_name: ""

- name: "RSS"
  url: "/feed.xml"
  title: "通过 RSS 订阅本网站"

- name: "技术参数"
  url: "https://tlo.xyz/wiki/ZE3kr/%E6%8A%80%E6%9C%AF%E5%8F%82%E6%95%B0"
  title: "关于本网站的技术参数"

- name: "隐私权"
  url: "https://tlo.xyz/wiki/TLO:%E9%9A%90%E7%A7%81%E6%94%BF%E7%AD%96"
  title: "关于隐私权"

- name: "捐款"
  url: "https://tlo.xyz/wiki/%E6%8D%90%E6%AC%BE"
  title: "感谢！"
