name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: us2-gcp.tloxygen.com
        username: ze3kr
        key: ${{ secrets.KEY }}
        fingerprint: SHA256:HPpFfjEmCHsGE3SENZkV4aDlBQlty+6wLI4AULeyrKE
        script: |-
          /usr/bin/git -C /home/ze3kr/sync/GuoZeyu.com pull
