name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: us1-gcp.s.tlo.xyz
        username: ze3kr
        key: ${{ secrets.KEY }}
        fingerprint: SHA256:5OrD23nnTU5qLNBlQd+XCOUoY/U1AvBfMEYWwgH3waM
        script: |-
          /usr/bin/git -C /home/ze3kr/sync/GuoZeyu.com reset --hard && /usr/bin/git -C /home/ze3kr/sync/GuoZeyu.com pull
