name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: bj1-aliyun.tloxygen.com
        username: ze3kr
        key: ${{ secrets.KEY }}
        script: cd git/guozeyu.com && npm install && npm build
