name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: us1-buyvm.tloxygen.com
        username: ze3kr
        key: ${{ secrets.KEY }}
        fingerprint: SHA256:mE3DP8yWRkRX+NIPZzDo6APiN7gINvp4l4gz6lbAw3c
        script: |-
          /usr/bin/git -C /home/ze3kr/sync/GuoZeyu.com pull &
          ssh us1-gcp.tloxygen.com '/usr/bin/git -C /home/ze3kr/sync/GuoZeyu.com pull' &
          ssh hk1-gcp.tloxygen.com '/usr/bin/git -C /home/ze3kr/sync/GuoZeyu.com pull' &
          ssh bj1-aliyun.tloxygen.com '/usr/bin/git -C /home/ze3kr/sync/GuoZeyu.com pull' &
          wait
